admin create user password field
inputlogic/flask-starter pull request #10
Opened 2017-07-13 00:01 UTC by arguingcrab

2017-07-13 00:14 UTC, adriaanwm commented
I believe this breaks the edit-user form because the user form is reused

2017-07-13 21:39 UTC, adriaanwm commented on app/views/admin/users.py
> +from app.forms.user import UserForm, CreateUserForm
should `UserForm` now be `EditUserForm` to be more explicit?

2017-07-17 23:36 UTC, adriaanwm commented
@geekforbrains why did you add "needs review" label here, is that as a reminder to review later, or am I misunderstanding how to use that label.

2017-07-18 17:57 UTC, geekforbrains commented on app/views/admin/users.py
> +from app.forms.user import UserForm, CreateUserForm
I don't think we need to rename to `EditUserForm` since create form is the only specific use case.

2017-07-18 17:58 UTC, geekforbrains requested changes
Needs rebase/conflicts fixed.

2017-07-18 18:13 UTC, geekforbrains approved these changes

2017-07-18 18:13 UTC, merged